godot check script

diff --git a/.github/workflows/godot-ci.yml b/.github/workflows/godot-ci.yml
--- a/.github/workflows/godot-ci.yml
+++ b/.github/workflows/godot-ci.yml
@@ -19,31 +19,31 @@ env:
   PROJECT_PATH: serious-jamm
  
 jobs:
-  test-compile:
-    name: GDScript Compile Check
-    runs-on: ubuntu-24.04
-    container:
-      image: barichello/godot-ci:4.3
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          lfs: true
-      - name: Setup
-        run: |
-          mkdir -v -p ~/.local/share/godot/export_templates/
-          mkdir -v -p ~/.config/
-          mv /root/.config/godot ~/.config/godot
-          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
-      - name: GDScript Compile Check
-        run: |
-          cd $PROJECT_PATH
-          godot --headless --quit-after 10 2>&1 | tee /tmp/godot-check.log
-          # Exit non-zero if any script errors were found
-          if grep -qiE "error|script failed|parse error" /tmp/godot-check.log; then
-            echo "Script errors detected!"
-            exit 1
-          fi
+  # test-compile:
+    # name: GDScript Compile Check
+    # runs-on: ubuntu-24.04
+    # container:
+      # image: barichello/godot-ci:4.3
+    # steps:
+      # - name: Checkout
+        # uses: actions/checkout@v4
+        # with:
+          # lfs: true
+      # - name: Setup
+        # run: |
+          # mkdir -v -p ~/.local/share/godot/export_templates/
+          # mkdir -v -p ~/.config/
+          # mv /root/.config/godot ~/.config/godot
+          # mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
+      # - name: GDScript Compile Check
+        # run: |
+          # cd $PROJECT_PATH
+          # godot --headless --quit-after 10 2>&1 | tee /tmp/godot-check.log
+          Exit non-zero if any script errors were found
+          # if grep -qiE "error|script failed|parse error" /tmp/godot-check.log; then
+            # echo "Script errors detected!"
+            # exit 1
+          # fi
  
   export-windows:
     name: Windows Export
